require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BookmarksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Bookmark. As you add validations to Bookmark, be sure to
  # adjust the attributes here as well.
  let(:bookmark) { FactoryGirl.create(:bookmark) }
  let(:valid_attributes) {  {name: "Google", url: "google.com", description: "Search the whole web", all_tags: "search"} }
  let(:invalid_attributes) { {name: '', url: "MyString", description: "MyString", all_tags: "tag1, tag2" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookmarksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bookmarks as @bookmarks" do
      get :index, {}, valid_session
      expect(assigns(:bookmarks)).to eq([bookmark])
    end
  end

  describe "GET #show" do
    it "assigns the requested bookmark as @bookmark" do
      get :show, {:id => bookmark.to_param}, valid_session
      expect(assigns(:bookmark)).to eq(bookmark)
    end
  end

  describe "GET #new" do
    it "assigns a new bookmark as @bookmark" do
      get :new, {}, valid_session
      expect(assigns(:bookmark)).to be_a_new(Bookmark)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bookmark as @bookmark" do
      get :edit, {:id => bookmark.to_param}, valid_session
      expect(assigns(:bookmark)).to eq(bookmark)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Bookmark" do
        expect {
          post :create, {:bookmark => valid_attributes}, valid_session
        }.to change(Bookmark, :count).by(1)
      end

      it "assigns a newly created bookmark as @bookmark" do
        post :create, {:bookmark => valid_attributes}, valid_session
        expect(assigns(:bookmark)).to be_a(Bookmark)
        expect(assigns(:bookmark)).to be_persisted
      end

      it "redirects to the created bookmark" do
        post :create, {:bookmark => valid_attributes}, valid_session
        expect(response).to redirect_to(Bookmark.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bookmark as @bookmark" do
        post :create, {:bookmark => invalid_attributes}, valid_session
        expect(assigns(:bookmark)).to be_a_new(Bookmark)
      end

      it "re-renders the 'new' template" do
        post :create, {:bookmark => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: "Bookmark2", url: "http://bookmark2.com", description: "Bookmark 2", all_tags: "tag3, tag4"}
      }

      it "updates the requested bookmark" do
        put :update, {:id => bookmark.to_param, :bookmark => new_attributes}, valid_session
        bookmark.reload
        updated_attrs = assigns(:bookmark).attributes.slice("name", "url", "description").merge("all_tags" => bookmark.all_tags).symbolize_keys
        expect(updated_attrs).to eq(new_attributes)
      end

      it "assigns the requested bookmark as @bookmark" do
        put :update, {:id => bookmark.to_param, :bookmark => valid_attributes}, valid_session
        expect(assigns(:bookmark)).to eq(bookmark)
      end

      it "redirects to the bookmark" do
        put :update, {:id => bookmark.to_param, :bookmark => valid_attributes}, valid_session
        expect(response).to redirect_to(bookmark)
      end
    end

    context "with invalid params" do
      it "assigns the bookmark as @bookmark" do
        put :update, {:id => bookmark.to_param, :bookmark => invalid_attributes}, valid_session
        expect(assigns(:bookmark)).to eq(bookmark)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => bookmark.to_param, :bookmark => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bookmark" do
      bookmark = FactoryGirl.create(:bookmark)
      expect {
        delete :destroy, {:id => bookmark.to_param}, valid_session
      }.to change(Bookmark, :count).by(-1)
    end

    it "redirects to the bookmarks list" do
      delete :destroy, {:id => bookmark.to_param}, valid_session
      expect(response).to redirect_to(bookmarks_url)
    end
  end

end
